FROM golang:alpine

RUN apk update && apk add --no-cache make\
        gcc\
        g++\
        libwebp\
        binutils-gold \
        curl \
        gnupg \
        libgcc \
        linux-headers \
        libwebp-dev\
        tiff-dev\
        libzip\
        libzip-dev
RUN go get -u github.com/cosmtrek/air
RUN go get -u github.com/kettek/apng


WORKDIR /go/src
CMD ["air", "-c", ".air.toml"]
