FROM --platform=linux/amd64 varnish:7.0.1-alpine

RUN apk add make cmake gcc g++ bash git automake autoconf libtool python3 py-docutils libssl1.1 libidn2-dev unbound-libs unbound-dev libuv-dev libevent-dev check-dev openssl-dev yaml-dev
RUN mkdir -p /tmp/vmods && \
    cd /tmp/vmods && \
    git clone --branch 7.0 --single-branch https://github.com/varnish/varnish-modules.git && \
    cd varnish-modules && \
     ./bootstrap && \
    ./configure && \
    make && \
    make install && \
    rm -rf /tmp/vmods

RUN mkdir -p /tmp/libgetdns && \
        cd /tmp/libgetdns && \
        git clone --branch v1.7.0 --single-branch https://github.com/getdnsapi/getdns.git && \
        cd getdns && git submodule update --init && \
        cmake . && \
        make && make install && \
        rm -rf /tmp/libgetdns
ENV VMODDIR=/usr/lib/varnish/vmods VARNISHSRC=/usr/include/varnish 
RUN mkdir -p /tmp/vmod-dynamic && \
    cd /tmp/vmod-dynamic && \
    git clone --branch 7.0 --single-branch https://github.com/nigoroll/libvmod-dynamic.git && \
    cd libvmod-dynamic && \
    ./autogen.sh && ./configure && make && make install && \
    rm -rf /tmp/vmod-dynamic
RUN apk del make cmake gcc g++ bash git automake autoconf python3 py-docutils

ADD varnish/default.vcl /etc/varnish/
ADD varnish/opts /etc/varnish/opts
ADD varnish/replaceenv.sh /
ADD varnish/entrypoint.sh /
RUN chmod 755 /replaceenv.sh
RUN chmod 755 /entrypoint.sh
CMD ["/bin/sh", "/entrypoint.sh"]
