FROM golang:alpine

WORKDIR /go/src
COPY ./go/src /go/src

RUN apk update && apk add --no-cache make\
        gcc\
        g++\
        libwebp\
        binutils-gold \
        curl \
        gnupg \
        libgcc \
        linux-headers \
        libwebp-dev\
        tiff-dev\
        libzip\
        libzip-dev\
        libjpeg-turbo-dev
RUN go get -u github.com/kettek/apng
RUN go get -u github.com/pixiv/go-libjpeg/jpeg

RUN go build -o /main


RUN adduser -S -D -H -h /app appuser
USER appuser

EXPOSE 8080
ENTRYPOINT ["/main"]
